//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aufgabe_4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public string Name { get; set; }
        public string Country { get; set; }
        public Nullable<decimal> Population { get; set; }
        public Nullable<decimal> Area { get; set; }
        public string Capital { get; set; }
        public string CapProv { get; set; }
    
        public virtual Country Country1 { get; set; }
    }
}
