//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prüfung1819
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bahnhoefe
    {
        public string Bundesland { get; set; }
        public string Regionalbereich { get; set; }
        public string Bahnhofsmanagement { get; set; }
        public int Bahnhofsnummer { get; set; }
        public string Station { get; set; }
        public string Abkuerzung_Betriebsstelle { get; set; }
        public string Bahnhofskategorie { get; set; }
        public string Strasse { get; set; }
        public Nullable<int> PLZ { get; set; }
        public string Ort { get; set; }
        public string Aufgabenträger { get; set; }
    }
}
