//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aufgabe_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parkplaetze
    {
        public int Parkplatz_Nr { get; set; }
        public string Name { get; set; }
        public Nullable<int> Bahnhofsnummer { get; set; }
        public string Betreiber { get; set; }
        public Nullable<int> Anzahl_Parkplaetze { get; set; }
        public string Ladestation { get; set; }
    }
}
