//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aufgabe3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aufzuege
    {
        public string TechnPlatzBezeichng { get; set; }
        public int Equipment { get; set; }
        public string Equipmentname { get; set; }
        public string Ort { get; set; }
        public Nullable<int> Bahnhofsnummer { get; set; }
        public string Hersteller { get; set; }
        public Nullable<int> Baujahr { get; set; }
    
        public virtual Bahnhoefe Bahnhoefe { get; set; }
    }
}
