//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aufgabe3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bahnhoefe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bahnhoefe()
        {
            this.Aufzuege = new HashSet<Aufzuege>();
            this.Bahnsteigdaten = new HashSet<Bahnsteigdaten>();
        }
    
        public string Bundesland { get; set; }
        public string Regionalbereich { get; set; }
        public string Bahnhofsmanagement { get; set; }
        public int Bahnhofsnummer { get; set; }
        public string Station { get; set; }
        public string Abkuerzung_Betriebsstelle { get; set; }
        public string Bahnhofskategorie { get; set; }
        public string Strasse { get; set; }
        public Nullable<int> PLZ { get; set; }
        public string Ort { get; set; }
        public string Aufgabenträger { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aufzuege> Aufzuege { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bahnsteigdaten> Bahnsteigdaten { get; set; }

        //public override string ToString()
        //{
        //    return Bahnhofsnummer + ". " + Station; 
        //}
    }
}
